---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  name: master-ap-south-1a
  labels:
    kops.k8s.io/cluster: ounass.k8s.local
spec:
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: "1"
    k8s.io/cluster-autoscaler/ounass.k8s.local: "1"
    kops.k8s.io/instance-selector: "1"
  role: Master
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20200716
  machineType: t2.micro
  minSize: 1
  maxSize: 1
  subnets:
    - ap-south-1a

# Instance Group 1: MixedInstancesPolicy
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: ounass.k8s.local
  name: mixed
spec:
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: "1"
    k8s.io/cluster-autoscaler/ounass.k8s.local: "1"
    kops.k8s.io/instance-selector: "1"
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20200528
  machineType: c3.xlarge
  maxSize: 15
  minSize: 2
  mixedInstancesPolicy:
    instances:
    - c3.xlarge
    - c4.xlarge
    - c5.xlarge
    - c5a.xlarge
    onDemandBaseCapacity: 1  # At least one on-demand instance
    onDemandPercentageAboveBaseCapacity: 50  # 50% of instances are on-demand
    spotAllocationStrategy: capacity-optimized
  nodeLabels:
    kops.k8s.io/instancegroup: mixed
  role: Node
  subnets:
  - ap-south-1a
  - ap-south-1b

# Instance Group 2: Lifecycle (on-demand)
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: ounass.k8s.local
  name: on-demand-group
spec:
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: "1"
    k8s.io/cluster-autoscaler/ounass.k8s.local: "1"
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20200716
  machineType: m4.large
  maxSize: 5
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: on-demand-group
  role: Node
  subnets:
  - ap-south-1a
  - ap-south-1b

# Instance Group 3: Lifecycle (Spot)
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: ounass.k8s.local
  name: spot-group
spec:
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: "1"
    k8s.io/cluster-autoscaler/ounass.k8s.local: "1"
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20200716
  machineType: m4.large
  maxSize: 10
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: spot-group
  role: Node
  subnets:
  - ap-south-1a
  - ap-south-1b
  instanceLifecycle: spot