{{- if .Values.configmap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
data:
  {{- range $name, $value := .Values.configmap.data }}
  {{ $name }}: {{ $value | quote }}
  {{- end }} 
{{- end }}