{{- if .Values.deployment }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- with .Values.deployment.selectorLabels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.deployment.annotations }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      {{- with .Values.deployment.selectorLabels }}
      {{ toYaml . | nindent 6 }}
      {{- end }}
  template:
    metadata:
      annotations:
        {{- with .Values.deployment.podAnnotations }}
        rollme: {{ randAlphaNum 5 | quote }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- with .Values.deployment.selectorLabels }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.deployment.deploySecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.deployment.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.deployment.imagePullSecrets }}
      {{- end }}
      containers:
        {{- range .Values.deployment.containers }}
        - name: {{ .name }}
          {{- with .securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .image.repository }}:{{ .image.tag  }}"
          imagePullPolicy: {{ .imagePullPolicy }}
          {{- if .volumeMounts }}
          volumeMounts:
            {{- with .volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          ports:
            {{- with .ports }}
            {{- range . }}
            - name: {{ .name }}
              containerPort: {{ .containerPort }}
              protocol: {{ .protocol }}
            {{- end }}
            {{- end }}
          {{- if .env }}
          env:
            {{- with .env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- if or .livenessProbe .readinessProbe }}
          livenessProbe:
            httpGet:
              path: {{ .livenessProbe.path | default "/" }}
              port: {{ .livenessProbe.port | default 80 }}
          readinessProbe:
            httpGet:
              path: {{ .readinessProbe.path | default "/" }}
              port: {{ .readinessProbe.port | default 80 }}
          {{- end }}
          resources:
            {{- toYaml .resources | nindent 12 }}
        {{- end }}
      {{- if .Values.deployment.volumes }}
      volumes:
        {{- with .Values.deployment.volumes }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
{{- end }}
