---
- name: Configure Nginx in Kops
  hosts: localhost
  become: yes  # Optional, if needed for your environment

  vars:
    shared_storage_path: "/Users/sharmrav/csv-uploader-data"
    domain_name: "casestudy.lab"
    ssl_certificate_file: "{{ shared_storage_path }}/certs/nginx-selfsigned.crt"
    ssl_certificate_key_file: "{{ shared_storage_path }}/certs/nginx-selfsigned.key"
    nginx_config_file: "{{ shared_storage_path }}/nginx.conf"

  tasks:
    - name: Create necessary directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ shared_storage_path }}"
        - "{{ shared_storage_path }}/certs"
        - "{{ shared_storage_path }}/html"

    - name: Generate a self-signed SSL certificate
      openssl_certificate:
        path: "{{ ssl_certificate_file }}"
        privatekey_path: "{{ ssl_certificate_key_file }}"
        csr_path: "{{ shared_storage_path }}/certs/nginx.csr"
        provider: selfsigned
        common_name: "{{ domain_name }}"
        subject:
          organizationName: "Ravi Sharma"
          organizationalUnitName: "IT Department"
        days: 365
      register: ssl_cert

    - name: Create a basic Nginx configuration file
      template:
        src: templates/nginx.conf.j2
        dest: "{{ nginx_config_file }}"
        mode: '0644'

  handlers:
    - name: Reload Nginx
      command: nginx -s reload
