---
- name: Configure Nginx
  hosts: localhost  # Replace with actual hostname/IP, update in inventory.ini
  become: yes # Assuming you have privileges to manage the container
  gather_facts: no

  vars:
    ssl_certificate_file: "/etc/nginx/ssl/cert.crt"  # Replace with your actual certificate path
    ssl_certificate_key_file: "/etc/nginx/ssl/cert.key"  # Replace with your actual key path
    domain_name: "rskelevraapp.com"  # Define the domain name here
    shared_storage_path: "/usr/share/nginx/html"  # Define the shared storage path here

  tasks:
    - name: Ensure sudo password is provided
      ansible.builtin.debug:
        msg: "This playbook requires sudo password. Make sure you have sudo access."

    - name: Create necessary directories
      file:
        path: /etc/nginx
        state: directory
        mode: '0755'

    - name: Create necessary directories
      file:
        path: /etc/nginx/ssl
        state: directory
        mode: '0755'

    - name: Deploy Nginx configuration file
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: '0644'

    - name: Create additional directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ shared_storage_path }}"
        - "/etc/nginx/ssl"

    - name: Check if Nginx configuration file exists
      stat:
        path: /etc/nginx/nginx.conf
      register: nginx_conf

    - name: Ensure Nginx is installed
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Deploy SSL certificate
      copy:
        src: "{{ ssl_certificate_file }}"
        dest: /etc/nginx/ssl/cert.crt
        remote_src: true
        mode: '0644'

    - name: Deploy SSL certificate key
      copy:
        src: "{{ ssl_certificate_key_file }}"
        dest: /etc/nginx/ssl/cert.key
        mode: '0600'