namespace: default

env:

service:
  type: NodePort
  ports:
    port: 80
    targetPort: 80
    nodePort: 30080
    name: http
  labels:
    app: "{{ .Release.Name }}"
  selector:
    app: "{{ .Release.Name }}"
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10  # Must be greater than 0
  targetCPUUtilizationPercentage: 80
  deploymentName: "csv-uploader"  # This should match your deployment's name
  secret:
  name: rskelevras-secret-helm
configmap:
  data:
    DATABASE_READER_URL: 'jdbc:postgresql://test.eu-west-1.rds.amazonaws.com/rskelevra'
    DATABASE_URL: 'jdbc:postgresql://test.eu-west-1.rds.amazonaws.com/rskelevra'
deployment:
  replicaCount: 1
  updatestrategy:
  selectorLabels:
    app: "{{ .Release.Name }}"
  livenessProbe:
    httpGet:
      path: /healthz
      port: 8080
    initialDelaySeconds: 3
    periodSeconds: 3
  readinessProbe:
    httpGet:
      path: /readiness
      port: 8080
    initialDelaySeconds: 3
    periodSeconds: 3
  containers:
    - name: nginx
      image:
        repository: nginx
        tag: "latest"
      ports:
        - containerPort: 80
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        seccompProfile:
          type: RuntimeDefault
        privileged: false
        readOnlyRootFilesystem: true
      volumeMounts:
        - name: shared-storage
          mountPath: /usr/share/nginx/html
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
    - name: webapp
      image:
        repository: rsharm49/casestudy
        tag: v0.2
      ports:
        - containerPort: 5000
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        seccompProfile:
          type: RuntimeDefault
      env:
      volumeMounts:
        - name: shared-storage
          mountPath: /app/static
      resources:
        requests:
          cpu: 250m
          memory: 250Mi
        limits:
          cpu: 500m
          memory: 500Mi
  imagePullSecrets: artifacthub-dummy-secret-new
  imagePullPolicy: Always
  volumes:
    - name: shared-storage
      emptyDir: {}